package com.ecop;
// Generated 17 Jul, 2015 8:37:23 PM by Hibernate Tools 3.6.0



/**
 * Complaint generated by hbm2java
 */
public class Complaint  implements java.io.Serializable {


     private Integer id;
     private PoliceStation policeStation;
     private Login login;
     private Criminal criminal;
     private String description;
     private String status;

    public Complaint() {
    }

	
    public Complaint(PoliceStation policeStation, Login login, String description) {
        this.policeStation = policeStation;
        this.login = login;
        this.description = description;
    }
    public Complaint(PoliceStation policeStation, Login login, Criminal criminal, String description, String status) {
       this.policeStation = policeStation;
       this.login = login;
       this.criminal = criminal;
       this.description = description;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PoliceStation getPoliceStation() {
        return this.policeStation;
    }
    
    public void setPoliceStation(PoliceStation policeStation) {
        this.policeStation = policeStation;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public Criminal getCriminal() {
        return this.criminal;
    }
    
    public void setCriminal(Criminal criminal) {
        this.criminal = criminal;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


