package com.ecop;
// Generated 17 Jul, 2015 8:37:23 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Criminal generated by hbm2java
 */
public class Criminal  implements java.io.Serializable {


     private String criminalId;
     private PoliceStation policeStation;
     private String name;
     private String gender;
     private String height;
     private String weight;
     private String crimelevel;
     private String status;
     private byte[] photo;
     private Set complaints = new HashSet(0);

    public Criminal() {
    }

	
    public Criminal(String criminalId, PoliceStation policeStation, String name, String gender, String height, String weight, String crimelevel, String status, byte[] photo) {
        this.criminalId = criminalId;
        this.policeStation = policeStation;
        this.name = name;
        this.gender = gender;
        this.height = height;
        this.weight = weight;
        this.crimelevel = crimelevel;
        this.status = status;
        this.photo = photo;
    }
    public Criminal(String criminalId, PoliceStation policeStation, String name, String gender, String height, String weight, String crimelevel, String status, byte[] photo, Set complaints) {
       this.criminalId = criminalId;
       this.policeStation = policeStation;
       this.name = name;
       this.gender = gender;
       this.height = height;
       this.weight = weight;
       this.crimelevel = crimelevel;
       this.status = status;
       this.photo = photo;
       this.complaints = complaints;
    }
   
    public String getCriminalId() {
        return this.criminalId;
    }
    
    public void setCriminalId(String criminalId) {
        this.criminalId = criminalId;
    }
    public PoliceStation getPoliceStation() {
        return this.policeStation;
    }
    
    public void setPoliceStation(PoliceStation policeStation) {
        this.policeStation = policeStation;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getHeight() {
        return this.height;
    }
    
    public void setHeight(String height) {
        this.height = height;
    }
    public String getWeight() {
        return this.weight;
    }
    
    public void setWeight(String weight) {
        this.weight = weight;
    }
    public String getCrimelevel() {
        return this.crimelevel;
    }
    
    public void setCrimelevel(String crimelevel) {
        this.crimelevel = crimelevel;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public Set getComplaints() {
        return this.complaints;
    }
    
    public void setComplaints(Set complaints) {
        this.complaints = complaints;
    }




}


