package com.ecop;
// Generated 17 Jul, 2015 8:37:23 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private String loginid;
     private String password;
     private String type;
     private String email;
     private String name;
     private Set complaints = new HashSet(0);

    public Login() {
    }

	
    public Login(String loginid, String password, String type) {
        this.loginid = loginid;
        this.password = password;
        this.type = type;
    }
    public Login(String loginid, String password, String type, String email, String name, Set complaints) {
       this.loginid = loginid;
       this.password = password;
       this.type = type;
       this.email = email;
       this.name = name;
       this.complaints = complaints;
    }
   
    public String getLoginid() {
        return this.loginid;
    }
    
    public void setLoginid(String loginid) {
        this.loginid = loginid;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getComplaints() {
        return this.complaints;
    }
    
    public void setComplaints(Set complaints) {
        this.complaints = complaints;
    }




}


