package com.ecop;
// Generated 17 Jul, 2015 8:37:23 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PoliceStation generated by hbm2java
 */
public class PoliceStation  implements java.io.Serializable {


     private String pstationId;
     private String pstationName;
     private String address;
     private int phone;
     private String pstationHead;
     private String password;
     private Set complaints = new HashSet(0);
     private Set criminals = new HashSet(0);

    public PoliceStation() {
    }

	
    public PoliceStation(String pstationId, String pstationName, String address, int phone, String pstationHead, String password) {
        this.pstationId = pstationId;
        this.pstationName = pstationName;
        this.address = address;
        this.phone = phone;
        this.pstationHead = pstationHead;
        this.password = password;
    }
    public PoliceStation(String pstationId, String pstationName, String address, int phone, String pstationHead, String password, Set complaints, Set criminals) {
       this.pstationId = pstationId;
       this.pstationName = pstationName;
       this.address = address;
       this.phone = phone;
       this.pstationHead = pstationHead;
       this.password = password;
       this.complaints = complaints;
       this.criminals = criminals;
    }
   
    public String getPstationId() {
        return this.pstationId;
    }
    
    public void setPstationId(String pstationId) {
        this.pstationId = pstationId;
    }
    public String getPstationName() {
        return this.pstationName;
    }
    
    public void setPstationName(String pstationName) {
        this.pstationName = pstationName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getPhone() {
        return this.phone;
    }
    
    public void setPhone(int phone) {
        this.phone = phone;
    }
    public String getPstationHead() {
        return this.pstationHead;
    }
    
    public void setPstationHead(String pstationHead) {
        this.pstationHead = pstationHead;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getComplaints() {
        return this.complaints;
    }
    
    public void setComplaints(Set complaints) {
        this.complaints = complaints;
    }
    public Set getCriminals() {
        return this.criminals;
    }
    
    public void setCriminals(Set criminals) {
        this.criminals = criminals;
    }




}


